src/Entity/Company.php
<?php

namespace App\Entity;

use App\Repository\CompanyRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CompanyRepository::class)
 */
class Company
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $website;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $phone_number;

     /**
     * @ORM\OneToMany(targetEntity="App\Entity\SummaryCompany", mappedBy="companies")
     */
    protected $studentCompanies;

    public function __construct()
    {
        $this->studentCompanies = new \Doctrine\Common\Collections\ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    /**
     * @return Collection|SummaryCompany[]|null
     */
    public function getSummaryCompanies(): Collection
    {
        return $this->summaryCompanies;
    }

    public function addSummaryCompany(SummaryCompany $summaryCompany): self
    {
        if (!$this->summaryCompanies->contains($summaryCompany)) {
            $this->summaryCompanies[] = $summaryCompany;
            $SummaryCompany->setCompany($this);
        }

        return $this;
    }

    public function removeSummaryCompany(SummaryCompany $summaryCompany): self
    {
        if ($this->summaryCompanies->contains($summaryCompany)) {
            $this->summaryCompanies->removeElement($summaryCompany);
            
            if ($summaryCompany->getCompany() === $this) {
                $summaryCompany->setCompany(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getName();
    }
}

src/Form/CompanyType.php
<?php

namespace App\Form;

use App\Entity\Company;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CompanyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('website')
            ->add('address')
            ->add('phone_number')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Company::class,
        ]);
    }
}

src/Controller/CompanyController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\ORM\EntityManagerInterface;
use App\Form\CompanyType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\CompanyRepository;
use App\Entity\SummaryCompany;
use App\Entity\Company;
use App\Entity\Summary;

/**
* @Route("/company", name="company.")
*/
class CompanyController extends AbstractController
{
    /**
     * @Route("/index", name="index")
     * @param CompanyRepository $companyRepository
     * @return Response
     */
    public function index(CompanyRepository $companyRepository): Response
    {
        $companies = $companyRepository->findAll();
        return $this->render('company/index.html.twig', [
            'controller_name' => 'CompanyController',
            'companies' => $companies,
        ]);
    }

    /**
     * @Route("/create", name="create", methods={"GET","POST"})
     * @param Request $request 
     * @return Response
     */
    public function create(Request $request): Response 
    {
        $company = new Company();

        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager= $this->getDoctrine()->getManager();
            $entityManager->persist($company);
            $entityManager->flush();

            $this->addFlash('success', 'Компанія успішно додана!');

            return $this->redirectToRoute('company.index');
        }

        return $this->render('company/create.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/edit/{id}", name="edit", methods={"GET","POST"})
     * @param Request $request 
     * @return Response
     */
    public function edit(Request $request, Company $company): Response
    {
        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', 'Компанія успішно змінена!');

            return $this->redirectToRoute('company.index');
        }

        return $this->render('company/edit.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/show/{id}", name="show", methods={"GET"})
     * @param Company $company
     * @param Request $request 
     * @return Response 
     */
    public function show(Request $request, Company $company, Summary $summary): Response 
    {      
        $companySummaries = $this->getDoctrine()->getManager()
        ->createQueryBuilder()
        ->select('sc, s.vacancy, s.createdAt, s.description')
        ->from(SummaryCompany::class, 'sc')
        ->innerJoin(Company::class, 'c', 'with', 'c.id = sc.companyId')
        ->innerJoin(Summary::class, 's', 'with', 's.id = sc.summaryId')
        ->where('c.id = :company_id')
        ->orderBy('sc.receivedAt', 'DESC')
        ->setParameter('company_id', $company->getId())
        ->getQuery()
        ->getResult();
        
        //dd($companySummaries);

        return $this->render('company/show.html.twig', [
            'companySummaries' => $companySummaries,
            'company' => $company,
        ]);
    }

    /**
     * @Route("/delete/{id}", name="delete")
     * @param Company $company 
     */
    public function remove(Company $company)
    {
        $entityManager= $this->getDoctrine()->getManager();
        $entityManager->remove($company);
        $entityManager->flush();
        
        $this->addFlash('success', 'Компанію успішно видалено!');

        return $this->redirect($this->generateUrl('company.index'));
    }
}

templates/company/_form.html.twig
{{ form_start(form) }}
    {{ form_row(form.name, {
        label: 'Компанія'
    }) }}
    {{ form_row(form.website, {
        label: 'Сайт'
    }) }}
    {{ form_row(form.address, {
        label: 'Адреса'
    }) }}
    {{ form_row(form.phone_number, {
        label: 'Телефон'
    }) }}
    <button class="btn btn-success"><i class='fas fa-plus-square'></i> Зберегти</button>
    <a class="btn btn-primary" href="{{ path('company.index') }}"><i class='fas fa-briefcase'></i> Список компаній</a>
{{ form_end(form) }}

templates/company/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Створення компанії{% endblock %}

{% block body %}
<div class="container mt-2">
    <div class="row">
        <div class="col-md-12">
        <h1 class="text-center">Форма створення нової компанії</h1>
        {{ include('company/_form.html.twig') }}
        </div>
    </div>
</div>
{% endblock %}

templates/company/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Редагування компанії{% endblock %}

{% block body %}
<div class="container mt-2">
    <div class="row">
        <div class="col-md-12">
        <h1>Форма редагування компанії</h1>
        {{ include('company/_form.html.twig', {'button_label': 'Змінити'}) }}
        </div>
    </div>
</div>
{% endblock %}

templates/company/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Компанії{% endblock %}

{% block body %}
<div class="container mt-2">
    <div class="row">
        <div class="col-md-12">
            {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
            <h1>Список компаній</h1>
            <a class="btn btn-success" href="{{ path('company.create') }}">
                <i class='fas fa-plus-square'></i> Додати компанію
            </a>
            <div class="table-responsive mt-3">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <td>Компанія</td>
                            <td>Сайт</td>                        
                            <td>Телефон</td>
                            <td style="width:8%">Дії</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for company in companies %}
                            <tr>
                                <td>{{ company.name }}</td>
                                <td>{{ company.website }}</td>
                                <td>{{ company.phoneNumber }}</td>
                                <td style="width:10%">
                                    <a style="text-decoration: none; margin-right: 3px" href="{{ path('company.show', {id: company.id}) }}">
                                        <i style="color: green" class='fas fa-eye'></i>
                                    </a>
                                    <a style="text-decoration: none; margin-right: 3px" href="{{ path('company.edit', {id: company.id}) }}">
                                        <i class='fas fa-edit'></i>
                                    </a>
                                    <a style="text-decoration: none; margin-right: 3px" href="{{ path('company.delete', {id: company.id}) }}">
                                        <i style="color: orangered" class='fas fa-trash'></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/company/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ company.name }} {% endblock %}

{% block body %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-info" href="{{ path('company.index') }}">
                <i class='fas fa-briefcase'></i> Список компаній
            </a>
            <a class="btn btn-primary" href="{{ path('company.edit', {id: company.id}) }}">
                <i class='fas fa-edit'></i> Змінити
            </a>
            <a class="btn btn-danger" href="{{ path('company.delete', {id: company.id}) }}">
                <i class='fas fa-trash'></i> Видалити
            </a>
            <div class="table-responsive mt-2">
                <table class="table table-bordered table-striped">
                    <tr>
                        <td>Компанія</td>
                        <td>{{ company.name }}</td>
                    </tr>
                    <tr>
                        <td>Сайт</td>
                        <td>{{ company.website }}</td>
                    </tr>
                    <tr>
                        <td>Адреса</td>
                        <td>{{ company.address }}</td>
                    </tr>
                    <tr>
                        <td>Телефон</td>
                        <td>{{ company.phoneNumber }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    {% if companySummaries > 0 %}
        <div class="row">
            <div class="col-md-6">  
                {% for sc in companySummaries %}
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="thumbnail text-center">
                            <p>{{ sc.vacancy }}</p>
                            <p>{{ sc.createdAt.format('d/m/Y H:i:s') }}</p>
                            <p>{{ sc.description }}</p>
                        </div>
                    </div>
                </div>            
                {% endfor %}
            </div>                  
        </div>
    </div>  
    {% endif %}  
</div>
{% endblock %}